from dateutil.tz import gettz

# Timezone mapping
TZINFOS = {
    "EST": gettz("US/Eastern"),
    "EDT": gettz("US/Eastern"),
    "CST": gettz("US/Central"),
    "CDT": gettz("US/Central"),
    "MST": gettz("US/Mountain"),
    "MDT": gettz("US/Mountain"),
    "PST": gettz("US/Pacific"),
    "PDT": gettz("US/Pacific"),
    "GMT": gettz("GMT"),
    "UTC": gettz("UTC"),
    "BST": gettz("Europe/London"),
    "CET": gettz("Europe/Paris"),
    "CEST": gettz("Europe/Paris"),
    "EET": gettz("Europe/Athens"),
    "EEST": gettz("Europe/Athens"),
    "IST": gettz("Asia/Kolkata"),
    "ACT": gettz("Australia/Darwin"),
    "ACST": gettz("Australia/Darwin"),
    "AET": gettz("Australia/Sydney"),
    "AEDT": gettz("Australia/Sydney"),
    "AEST": gettz("Australia/Brisbane"),
    "AWT": gettz("Australia/Perth"),
    "AWDT": gettz("Australia/Perth"),
    "WET": gettz("Europe/Lisbon"),
    "WEST": gettz("Europe/Lisbon"),
    "HST": gettz("Pacific/Honolulu"),
    "AKST": gettz("America/Anchorage"),
    "AKDT": gettz("America/Anchorage"),
    "CHST": gettz("Pacific/Guam"),
    "NZST": gettz("Pacific/Auckland"),
    "NZDT": gettz("Pacific/Auckland"),
    "AST": gettz("America/Puerto_Rico"),
    "ADT": gettz("America/Halifax"),
    "SST": gettz("Pacific/Midway"),
    "WAT": gettz("Africa/Lagos"),
    "CAT": gettz("Africa/Harare"),
    "EAT": gettz("Africa/Nairobi"),
    "SAST": gettz("Africa/Johannesburg"),
    "MSK": gettz("Europe/Moscow"),
    "CCT": gettz("Indian/Cocos"),
    "JST": gettz("Asia/Tokyo"),
    "KST": gettz("Asia/Seoul"),
    "HKT": gettz("Asia/Hong_Kong"),
    "SGT": gettz("Asia/Singapore"),
    "MYT": gettz("Asia/Kuala_Lumpur"),
    "WIB": gettz("Asia/Jakarta"),
    "WITA": gettz("Asia/Makassar"),
    "WIT": gettz("Asia/Jayapura"),
}
